import { euro } from './shared'

// Copy for the trade hubs, region hubs and price pages.
export const HUBS = {
  fr: {
    tradeTitle: t => `${t.name.fr} : dépannage 24h/24, prix annoncé | Bruxelles et Brabant`,
    tradeDesc: (t, r) => `${t.name.fr} à Bruxelles, en Brabant wallon et en Brabant flamand. Prix fixes de ${euro(r.low)} à ${euro(r.high)}, annoncés avant le déplacement. Réservation en ligne.`,
    tradeH1: t => `${t.name.fr} à Bruxelles et dans le Brabant`,
    tradeLead: t => `Des ${t.plural.fr} indépendants, vérifiés, avec une fourchette de prix annoncée avant chaque déplacement. Choisissez votre zone pour voir les communes couvertes.`,
    regionTitle: (t, r) => `${t.name.fr} ${r.in.fr} : urgence 24h/24, prix fixes`,
    regionDesc: (t, r, from) => `${t.name.fr} ${r.in.fr} dès ${euro(from)} TTC. Prix annoncé avant le déplacement, paiement après l’intervention. Toutes les communes ${r.in.fr}.`,
    regionH1: (t, r) => `${t.name.fr} ${r.in.fr}`,
    regionLead: (t, r, n) => `${n} communes couvertes ${r.in.fr}. Un ${t.name.fr.toLowerCase()} indépendant de la zone, un prix annoncé avant son départ et une facture détaillée.`,
    regionIntro: {
      bruxelles: t => `Dans les 19 communes bruxelloises, les interventions se font surtout en appartement : portes palières, immeubles avec parties communes, maisons de maître divisées. Nos ${t.plural.fr} connaissent ces configurations et vous disent avant de commencer qui, du locataire, du propriétaire ou du syndic, prend en charge la facture.`,
      'brabant-wallon': t => `En Brabant wallon, les distances entre villages sont plus grandes et les maisons ont souvent plusieurs accès et des annexes. Nos ${t.plural.fr} interviennent de Waterloo à Jodoigne et de Tubize à Perwez, avec le même prix partout dans la province.`,
      'brabant-flamand': t => `En Brabant flamand, nos ${t.plural.fr} interviennent en français et en néerlandais, de la périphérie bruxelloise (Wemmel, Zaventem, Rhode-Saint-Genèse) jusqu’à Louvain, Tirlemont et Diest.`,
    },
    communesTitle: r => `Communes couvertes ${r.in.fr}`,
    regionsTitle: 'Choisissez votre zone',
    faq: (t, fees) => [
      { q: `Le prix d’un ${t.name.fr.toLowerCase()} est-il vraiment fixe ?`, a: `Vous recevez une fourchette par prestation avant le déplacement. Le prix final reste dans cette fourchette ; si l’artisan découvre un problème différent sur place, il vous fait un devis et vous restez libre de refuser (seuls ${euro(fees.travel)} de déplacement et diagnostic sont alors dus).` },
      { q: 'Y a-t-il un supplément la nuit ou le week-end ?', a: `Oui, une seule majoration de ${euro(fees.surcharge)} entre 20h et 8h, le week-end et les jours fériés. Elle ne se cumule pas et vous est annoncée avant le déplacement.` },
      { q: 'Comment payer ?', a: 'Après l’intervention, directement à l’artisan, par carte, virement ou paiement mobile. Vous recevez une facture détaillée.' },
    ],
    pricesIndexTitle: 'Prix des dépannages à domicile en 2026 : grilles TTC',
    pricesIndexDesc: 'Grilles de prix TTC par prestation pour Bruxelles, le Brabant wallon et le Brabant flamand : fourchettes fixes, majorations et TVA expliquées.',
    pricesIndexH1: 'Nos prix, prestation par prestation',
    pricesIndexLead: 'Chaque fourchette comprend le déplacement, la main-d’œuvre et les petites fournitures, TVA 6 % comprise. Elle vous est confirmée avant le déplacement de l’artisan.',
    pricesTitle: t => `Prix ${t.name.fr.toLowerCase()} 2026 : grille complète TTC | Bruxelles et Brabant`,
    pricesDesc: (t, r) => `Combien coûte un ${t.name.fr.toLowerCase()} ? De ${euro(r.low)} à ${euro(r.high)} selon la prestation. Grille complète, majorations nuit et week-end, TVA 6 ou 21 %.`,
    pricesH1: t => `Prix d’un ${t.name.fr.toLowerCase()} en 2026`,
    pricesLead: t => `La grille complète de nos ${t.plural.fr}, TVA comprise. Le prix vous est annoncé avant le déplacement et vous payez après l’intervention.`,
    method: 'Comment nous fixons ces prix',
    methodText: 'Les fourchettes sont établies avec les artisans partenaires à partir de la durée moyenne de chaque prestation, du coût des fournitures courantes et des prix pratiqués en Belgique. La borne basse correspond à une intervention simple, la borne haute à une configuration plus difficile (porte blindée, accès compliqué, pièce spécifique).',
  },
  nl: {
    tradeTitle: t => `${t.name.nl}: 24/7 hulp, prijs vooraf gekend | Brussel en Brabant`,
    tradeDesc: (t, r) => `${t.name.nl} in Brussel en Vlaams-Brabant. Vaste prijzen van ${euro(r.low)} tot ${euro(r.high)}, gekend vóór vertrek. Online reserveren.`,
    tradeH1: t => `${t.name.nl} in Brussel en Vlaams-Brabant`,
    tradeLead: t => `Zelfstandige, gecontroleerde ${t.plural.nl} met een prijsvork die u kent vóór elke verplaatsing. Kies uw regio om de gemeenten te zien.`,
    regionTitle: (t, r) => `${t.name.nl} ${r.in.nl}: 24/7, vaste prijzen`,
    regionDesc: (t, r, from) => `${t.name.nl} ${r.in.nl} vanaf ${euro(from)} incl. btw. Prijs gekend vóór vertrek, betalen na de interventie. Alle gemeenten ${r.in.nl}.`,
    regionH1: (t, r) => `${t.name.nl} ${r.in.nl}`,
    regionLead: (t, r, n) => `${n} gemeenten ${r.in.nl}. Een zelfstandige ${t.name.nl.toLowerCase()} uit de buurt, een prijs die u vooraf kent en een gedetailleerde factuur.`,
    regionIntro: {
      bruxelles: t => `In de 19 Brusselse gemeenten gaat het vooral om appartementen: voordeuren van flats, gebouwen met gemeenschappelijke delen, opgesplitste herenhuizen. Onze ${t.plural.nl} kennen die situaties en zeggen vooraf wie de factuur betaalt: huurder, eigenaar of syndicus.`,
      'brabant-wallon': t => `In Waals-Brabant zijn de afstanden groter en hebben woningen vaak meerdere toegangen en bijgebouwen.`,
      'brabant-flamand': t => `In Vlaams-Brabant werken onze ${t.plural.nl} in het Nederlands en het Frans, van de Brusselse rand (Wemmel, Zaventem, Sint-Genesius-Rode) tot Leuven, Tienen en Diest.`,
    },
    communesTitle: r => `Gemeenten ${r.in.nl}`,
    regionsTitle: 'Kies uw regio',
    faq: (t, fees) => [
      { q: `Is de prijs van een ${t.name.nl.toLowerCase()} echt vast?`, a: `U krijgt per interventie een prijsvork vóór de verplaatsing. De eindprijs blijft binnen die vork; ontdekt de vakman ter plaatse een ander probleem, dan krijgt u een offerte en mag u weigeren (dan betaalt u enkel ${euro(fees.travel)} verplaatsing en diagnose).` },
      { q: "Is er een toeslag 's nachts of in het weekend?", a: `Ja, één toeslag van ${euro(fees.surcharge)} tussen 20u en 8u, in het weekend en op feestdagen. Nooit gecumuleerd en vooraf gemeld.` },
      { q: 'Hoe betaal ik?', a: 'Na de interventie, rechtstreeks aan de vakman, met kaart, overschrijving of mobiel betalen. U krijgt een gedetailleerde factuur.' },
    ],
    pricesIndexTitle: 'Prijzen 2026: slotenmaker, loodgieter, elektricien, chauffagist',
    pricesIndexDesc: 'Prijzen incl. btw per interventie voor Brussel en Vlaams-Brabant: vaste prijsvorken, toeslagen en btw uitgelegd.',
    pricesIndexH1: 'Onze prijzen, interventie per interventie',
    pricesIndexLead: 'Elke prijsvork omvat verplaatsing, werkuren en klein materiaal, incl. 6 % btw. U krijgt ze bevestigd vóór de vakman vertrekt.',
    pricesTitle: t => `Prijs ${t.name.nl.toLowerCase()} 2026: volledige lijst incl. btw`,
    pricesDesc: (t, r) => `Hoeveel kost een ${t.name.nl.toLowerCase()}? Van ${euro(r.low)} tot ${euro(r.high)} per interventie. Volledige lijst, toeslagen en btw 6 of 21 %.`,
    pricesH1: t => `Prijs van een ${t.name.nl.toLowerCase()} in 2026`,
    pricesLead: t => `De volledige prijslijst van onze ${t.plural.nl}, btw inbegrepen. U kent de prijs vóór vertrek en betaalt na de interventie.`,
    method: 'Hoe we deze prijzen bepalen',
    methodText: 'De prijsvorken zijn opgesteld met onze partnervakmensen op basis van de gemiddelde duur van elke interventie, de kost van courant materiaal en de prijzen in België. De onderkant geldt voor een eenvoudige interventie, de bovenkant voor een moeilijkere situatie (veiligheidsdeur, moeilijke toegang, specifiek onderdeel).',
  },
}
